version: '3.1'

services:

  baseconhecimento:
    container_name: baseconhecimento
    hostname: baseconhecimento
    image: wordpress:5.1-php7.1-apache
    restart: always
    privileged: true
    ports:
      - 80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: 71UjqFIgyzEG
      WORDPRESS_DB_NAME: knowledgebase 
      WORDPRESS_TABLE_PREFIX: kb_
    labels:
      - traefik.enabled=true
      - traefik.backend=baseconhecimento
      - traefik.frontend.rule=Host:baseconhecimento.mme.gov.br
      - traefik.docker.network=composes_front
      - traefik.port=80
    external_links:
      - mysql:mysql
    volumes:
    - /opt/knowledgebase/:/var/www/html
    networks:
      front:
        ipv4_address: 172.36.238.17


networks:
    front:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.36.238.0/24
